replicaCount: 2

image:
  repository: {{ .Values.awsAccountId }}.dkr.ecr.us-east-1.amazonaws.com/my-ecr-repo
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 3000
